const FETCHING_SINGLE_NOTE = 'FETCHING_SINGLE_NOTE';
const FETCHED_SINGLE_NOTE = 'FETCHED_SINGLE_NOTE';

const DELETING_SINGLE_NOTE = 'DELETING_SINGLE_NOTE';
const DELETE_SINGLE_NOTE = 'DELETE_SINGLE_NOTE';

export default {
    FETCHING_SINGLE_NOTE,
    FETCHED_SINGLE_NOTE,
    DELETING_SINGLE_NOTE,
    DELETE_SINGLE_NOTE
}