export const notes = [
  {
    id: 0,
    title: 'Thinking about things',
    body:
      "My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?\n The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee."
  },
  {
    id: 1,
    title: "Hmm that's interesting?",
    body:
      "Unicorn kinfolk listicle, trust fund wolf literally normcore yr hammock post-ironic salvia. Whatever keffiyeh bespoke, blog authentic poke narwhal. Intelligentsia swag 8-bit hot chicken fanny pack vaporware flexitarian brooklyn unicorn thundercats jean shorts umami green juice jianbing put a bird on it. Gluten-free lumbersexual salvia echo park, shabby chic direct trade migas adaptogen pabst sartorial trust fund. Fam messenger bag fanny pack beard you probably haven't heard of them organic poke gastropub iceland shoreditch vexillologist forage lo-fi raclette. Single-origin coffee fixie try-hard, fam before they sold out cloud bread tote bag glossier squid williamsburg. Godard seitan tumeric portland keytar chia migas bicycle rights meh church-key green juice flexitarian thundercats.\n Farm-to-table snackwave green juice cold-pressed chambray. Salvia humblebrag mumblecore heirloom, pitchfork raclette roof party four loko hella banjo tattooed pug palo santo normcore. Dreamcatcher coloring book fam, taiyaki succulents forage hexagon taxidermy blog migas. Shabby chic waistcoat la croix af. Whatever mixtape poutine adaptogen deep v copper mug paleo.\n Oh. You need a little dummy text for your mockup? How quaint.\n I bet you’re still using Bootstrap too…"
  },
  {
    id: 2,
    title: 'Workout Info',
    body:
      "Lorem ipsum dolor amet squid fingerstache pour-over disrupt put a bird on it shaman. Gentrify gluten-free church-key, umami chambray dreamcatcher squid succulents lo-fi vinyl. Before they sold out kinfolk viral fingerstache jean shorts. Post-ironic gluten-free ugh selfies. Green juice cloud bread banh mi, fingerstache pork belly sartorial helvetica gentrify jean shorts. Post-ironic copper mug unicorn blog, pork belly irony keffiyeh 3 wolf moon portland iPhone twee dreamcatcher.\n Deep v blog selfies salvia, +1 locavore kinfolk. Man braid slow-carb hell of sriracha, kombucha godard before they sold out disrupt occupy kitsch snackwave. Man braid unicorn vegan pabst schlitz celiac cray shaman activated charcoal four loko. Kinfolk shoreditch cray, leggings fixie austin church-key pour-over copper mug put a bird on it beard. Fashion axe umami neutra cardigan hoodie. Selfies adaptogen typewriter quinoa echo park heirloom taxidermy pabst, meggings forage PBR&B. YOLO jean shorts meh fanny pack.\n Chillwave truffaut PBR&B, iPhone helvetica man bun post-ironic swag mumblecore semiotics leggings hell of. Schlitz kogi leggings, vinyl bushwick meditation microdosing pour-over yuccie taxidermy ethical asymmetrical enamel pin. Enamel pin prism cliche, gentrify fashion axe synth asymmetrical listicle. Portland tilde squid before they sold out pork belly kinfolk semiotics ethical tousled 3 wolf moon single-origin coffee DIY. Deep v lomo twee, brooklyn iPhone gastropub raw denim asymmetrical ethical bushwick. Gastropub organic cronut before they sold out.\n Kinfolk 90's aesthetic put a bird on it raclette. Before they sold out brunch crucifix, literally cold-pressed portland scenester yuccie organic tofu roof party cardigan hammock pour-over whatever. Letterpress kombucha keffiyeh, roof party skateboard poke lo-fi four loko tattooed tumblr truffaut echo park af. Affogato chillwave woke tilde pickled beard microdosing YOLO celiac poutine ramps wolf mumblecore typewriter. Banh mi plaid retro jean shorts bespoke cornhole live-edge slow-carb, taxidermy biodiesel succulents seitan pok pok adaptogen yr.\n Tacos quinoa gochujang messenger bag ramps tousled asymmetrical vexillologist. Typewriter dreamcatcher food truck ramps wayfarers activated charcoal affogato, franzen beard mlkshk sustainable single-origin coffee letterpress. Mustache asymmetrical retro vaporware, tofu freegan direct trade pickled XOXO echo park hella small batch. Yr meggings migas kitsch master cleanse viral knausgaard VHS gluten-free woke live-edge brooklyn banh mi twee messenger bag."
  },
  {
    id: 3,
    title: 'Thinking about the sky',
    body:
      "Quasar at the edge of forever Cambrian explosion vastness is bearable only through love intelligent beings invent the universe. Rich in mystery tesseract star stuff harvesting star light white dwarf rings of Uranus ship of the imagination. Citizens of distant epochs stirred by starlight the carbon in our apple pies citizens of distant epochs stirred by starlight rings of Uranus. Hundreds of thousands something incredible is waiting to be known how far away not a sunrise but a galaxyrise made in the interiors of collapsing stars bits of moving fluff.\n The sky calls to us colonies rogue made in the interiors of collapsing stars astonishment Jean-François Champollion? A still more glorious dawn awaits encyclopaedia galactica venture hundreds of thousands rings of Uranus something incredible is waiting to be known. Vanquish the impossible a mote of dust suspended in a sunbeam Sea of Tranquility muse about vastness is bearable only through love from which we spring. Something incredible is waiting to be known take root and flourish two ghostly white figures in coveralls and helmets are soflty dancing dream of the mind's eye take root and flourish another world.\n Billions upon billions tendrils of gossamer clouds galaxies Euclid inconspicuous motes of rock and gas vastness is bearable only through love? Paroxysm of global death at the edge of forever muse about are creatures of the cosmos Sea of Tranquility extraordinary claims require extraordinary evidence? Vanquish the impossible invent the universe invent the universe at the edge of forever vanquish the impossible extraordinary claims require extraordinary evidence? Gathered by gravity something incredible is waiting to be known a mote of dust suspended in a sunbeam laws of physics the only home we've ever known hearts of the stars and billions upon billions upon billions upon billions upon billions upon billions upon billions."
  },
  {
    id: 4,
    title: 'MISSISSIPPI',
    body:
      "Pommy ipsum bit of a Jack the lad off t'shop ever so, throw a paddy the black death. Moriarty Weeping Angels have a butcher's at this what a load of guff and we all like figgy pudding cup of tea codswallop driving a mini bit of alright scouser conkers, bag egg's old boy Amelia Pond a comely wench by 'eck love scatterbrained baffled Weeping Angels I bid you good day splendid. Ended up brown bread ridicule lad tallywhacker nutter guinness the dog's dinner cor blimey', jolly good a cracking nose rag what a load of guff a cracking. Victoria sponge cake nuthouse Dalek scrote down South brown sauce, fish fingers and custard bobby football.\n On the beat scones squirrel clotted cream the fuzz in the goolies ever so, working class ended up brown bread anorak crisps rivetting stuff. Slap-head knackered cor blimey' Dalek because there was nothing on the gogglebox Sonic Screwdriver, tally-ho nigh alright duck how's your father, tad lug hole nonsense spam fritters. Terribly drizzle clotted cream taking the mick Dalek stop arsing around tip-top, slap-head pezzy little lass lad The Hounds of Baskerville unhand me sir drizzle, off with her head twiglets chips getting on my wick bag egg's old boy.\n Down South and we all like figgy pudding bossy britches by 'eck love, gobsmacked ridiculous."
  },
  {
    id: 5,
    title: 'Boating Information',
    body:
      "Coxswain to go on account spyglass hornswaggle hail-shot Jack Ketch Jack Tar lad take a caulk Barbary Coast. Lanyard overhaul Privateer coffer dead men tell no tales Brethren of the Coast draught haul wind pink case shot. Black spot belaying pin Gold Road rope's end chase guns pinnace me grog blossom heave down careen.\n Nipper quarter wench Sail ho strike colors gun ye run a rig yardarm log. Jib take a caulk starboard Plate Fleet landlubber or just lubber hornswaggle Davy Jones' Locker Cat o'nine tails chandler man-of-war. Crimp fore heave down topsail draft Admiral of the Black grog blossom topmast squiffy hearties.\n Execution dock brigantine broadside piracy bilged on her anchor long boat line draft Admiral of the Black to go on account. Blow the man down bowsprit bilge water lanyard rum galleon sloop Yellow Jack yard scuppers. Run a rig quarterdeck gibbet topsail bowsprit doubloon mizzen sheet rigging crack Jennys tea cup."
  },
  {
    id: 6,
    title: 'Groceries',
    body:
      'Chevron stiff upper lip got milk fu manchu freestyle, goose freestyle graeme souness cappuccino catcher rugged et stiff upper lip holiday waiter chevron prostate cancer got milk barber shop quartet bad guy fu manchu.\n Cappuccino collector jolly good show man of the year 1986 prince barin tricky sneezes face mop hairy kid at school marquess of queensbury, handsome tricky sneezes marquess of queensbury smashing good fun hairy kid at school john aldridge lemmy fox hunting nuremberg rally prince barin Fallen eyebrow man of the year 1986 cappuccino collector face mop jolly good show. East european ian rush dolor sit amet kris kristofferson. lorreto del mar clive dunn mustachioed lip warmer, east european mustachioed ian rush dis lorreto del mar crumb catcher dolor sit amet lipwig clive dunn kris kristofferson. prince barin lip warmer.\n Consectetur ian rush elit yeoman farmer village people socially mobile derek griffiths, mexican’t derek griffiths magnum pi robert winston ian rush elit sam elliott yeoman farmer village people 118 118 consectetur socially mobile, village people mexican’t sam elliott cigars 118 118 robert winston socially mobile ian rush ron jeremy elit ned flanders derek griffiths magnum pi consectetur yeoman farmer\n Challenge you to a duel elit frightfully nice. Doctor strange sam elliott hairy kiss. cripes wario, boogie nights blacksmith hairy kiss. wario sam elliott doctor strange dali cripes country baron toothbrush, cripes sam elliott mexican’t alpha trion Sergeant major barber shop quartet dali toothbrush country baron doctor strange wario boogie nights blacksmith hairy kiss..'
  },
  {
    id: 7,
    title: 'Shower Thoughts',
    body:
      "These days are all Happy and Free. These days are all share them with me oh baby. Here he comes Here comes Speed Racer. He's a demon on wheels. Maybe you and me were never meant to be. But baby think of me once in awhile. I'm at WKRP in Cincinnati. Knight Rider: A shadowy flight into the dangerous world of a man who does not exist. Believe it or not I'm walking on air. I never thought I could feel so free. And if you threw a party - invited everyone you knew. You would see the biggest gift would be from me and the card attached would say thank you for being a friend. So join us here each week my friends you're sure to get a smile from seven stranded castaways here on Gilligans Isle. Come and play. Everything's A-OK. Friendly neighbors there that's where we meet. Can you tell me how to get how to get to Sesame Street.\n And if you threw a party - invited everyone you knew. You would see the biggest gift would be from me and the card attached would say thank you for being a friend. black gold But they got diff'rent strokes. It takes diff'rent strokes - it takes diff'rent strokes to move the world. He's gainin' on you so you better look alive. He busy revin' up his Powerful Mach 5. Just two good ol' boys Never meanin' no harm. Beats all you've ever saw been in trouble with the law since the day they was born. Fish don't fry in the kitchen and beans don't burn on the grill. Took a whole lotta tryin' just to get up that hill. And we know Flipper lives in a world full of wonder flying there-under under the sea? Their house is a museum where people come to see ‘em. They really are a scream the Addams Family. No phone no lights no motor car not a single luxury. Like Robinson Crusoe it's primitive as can be.\n Well we're movin' on up to the east side to a deluxe apartment in the sky. Believe it or not I'm walking on air. I never thought I could feel so free. Flying away on a wing and a prayer. Who could it be? Believe it or not its just me."
  },
  {
    id: 8,
    title: 'Mystery Dinner Ideas',
    body:
      "Straightnin' the curves. Flatnin' the hills Someday the mountain might get ‘em but the law never will. In 1972 a crack commando unit was sent to prison by a military court for a crime they didn't commit. These men promptly escaped from a maximum security stockade to the Los Angeles underground. They were four men living all together yet they were all alone. The movie star the professor and Mary Ann here on Gilligans Isle. The mate was a mighty sailin' man the Skipper brave and sure. Five passengers set sail that day for a three hour tour a three hour tour. Come and knock on our door. We've been waiting for you. Where the kisses are hers and hers and his. Three's company too. Well the first thing you know ol' Jeds a millionaire. Kinfolk said Jed move away from there. Their house is a museum where people come to see ‘em. They really are a scream the Addams Family. Believe it or not I'm walking on air. I never thought I could feel so free. Flying away on a wing and a prayer. Who could it be? Believe it or not its just me. Well we're movin' on up to the east side. To a deluxe apartment in the sky. Flying away on a wing and a prayer. Who could it be? Believe it or not its just me.\n No phone no lights no motor car not a single luxury. Like Robinson Crusoe it's primitive as can be. Just two good ol' boys Never meanin' no harm. Beats all you've ever saw been in trouble with the law since the day they was born. Why do we always come here? I guess well never know. Its like a kind of torture to have to watch the show?"
  }
];
