export const GETTING_NOTES = "GETTING_NOTES"
export const GOT_NOTES = "GOT_NOTES"
export const ADDING_NOTE = "ADDING_NOTE"
export const ADDED_NOTE = "ADDED_NOTE"
export const EDITING_NOTE = "EDITING_NOTE"
export const EDITED_NOTE = "EDITED_NOTE"
export const EDITED_NOTE = "EDITED_NOTE"