const dummyData = [
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamcorper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "I AM 3",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamcorper   . Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
  {
    title: "Note Title",
    content:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sem velit, rutrum sit amet commodo sit amet, tempus non lacus. In posuere a quam ac ullamco   rper. Vestibulum semper, felis accumsan tempor vulputate, risus leo ornare ante, sit amet feugiat metus libero eu erat. Sed gravida urna gravida turpis lobortis, id scelerisque sapien malesuada. Vivamus iaculis eleifend erat eget sodales. Curabitur efficitur scelerisque tortor eget pretium. Quisque at leo eu risus mollis auctor. Curabitur ut vestibulum odio, in cursus risus. Maecenas molestie nibh ut iaculis fermentum. In vehicula ligula vitae pulvinar aliquet. Cras ligula magna, vulputate in faucibus sed, blandit aliquam sem. In tempor facilisis enim eu placerat. Donec congue lobortis orci, sit amet maximus ipsum sollicitudin non.Curabitur varius turpis eu ornare molestie. Mauris bibendum tellus ut mauris vestibulum, ac elementum ligula euismod. Donec interdum consequat sem, eget feugiat sapien tristique eget. Cras non aliquam justo. In id urna nec lacus sagittis pellentesque. Etiam malesuada aliquet tincidunt. Quisque ac mi mattis, faucibus eros eget, mattis dui. Cras tincidunt accumsan justo sit amet lobortis. Etiam id mattis ipsum, sed interdum sem. Ut euismod eros ut porta convallis. Pellentesque accumsan imperdiet diam, non pharetra ex ultricies eu."
  },
];

export default dummyData;   