export { 
    NOTES_FETCH_START,
    NOTES_FETCH_COMPLETE,
    NOTES_FETCH_FAILURE,

    ADD_NOTE_START,
    ADD_NOTE_COMPLETE,
    ADD_NOTE_FAILURE,

    NOTE_GET_START,
    NOTE_GET_COMPLETE,
    NOTE_GET_FAILURE,

    NOTE_EDIT_START,
    NOTE_EDIT_COMPLETE,
    NOTE_EDIT_FAILURE,

    DELETE_NOTE_START,
    DELETE_NOTE_COMPLETE,
    DELETE_NOTE_FAILURE,

    getNoteList,
    addNewNote,
    getNote,
    editNote,
    deleteNote
} from './notesActions';