const GET_NOTES = 'GET_NOTES'
const GET_NOTES_SUCCESS = 'GET_NOTES_SUCCESS'
const GET_NOTES_ERROR = 'GET_NOTES_ERROR'

const ADD_NOTE = 'ADD_NOTE'
const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS'
const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR'

const DELETE_NOTE = 'DELETE_NOTE'



const UDPATE_NOTE = 'UPDATE_NOTE'